package org.capten.live.model;

import java.util.Date;

public class AwardShop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.award_shop.id
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Object id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.award_shop.user_id
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Object userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.award_shop.name
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.award_shop.introduce
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private String introduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.award_shop.cover_img
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private String coverImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.award_shop.num
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.award_shop.is_delete
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.award_shop.create_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.award_shop.update_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.award_shop.starts
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Integer starts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.award_shop.version
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.award_shop.id
     *
     * @return the value of public.award_shop.id
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Object getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.award_shop.id
     *
     * @param id the value for public.award_shop.id
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setId(Object id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.award_shop.user_id
     *
     * @return the value of public.award_shop.user_id
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Object getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.award_shop.user_id
     *
     * @param userId the value for public.award_shop.user_id
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setUserId(Object userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.award_shop.name
     *
     * @return the value of public.award_shop.name
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.award_shop.name
     *
     * @param name the value for public.award_shop.name
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.award_shop.introduce
     *
     * @return the value of public.award_shop.introduce
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.award_shop.introduce
     *
     * @param introduce the value for public.award_shop.introduce
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.award_shop.cover_img
     *
     * @return the value of public.award_shop.cover_img
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public String getCoverImg() {
        return coverImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.award_shop.cover_img
     *
     * @param coverImg the value for public.award_shop.cover_img
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setCoverImg(String coverImg) {
        this.coverImg = coverImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.award_shop.num
     *
     * @return the value of public.award_shop.num
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.award_shop.num
     *
     * @param num the value for public.award_shop.num
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.award_shop.is_delete
     *
     * @return the value of public.award_shop.is_delete
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.award_shop.is_delete
     *
     * @param isDelete the value for public.award_shop.is_delete
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.award_shop.create_time
     *
     * @return the value of public.award_shop.create_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.award_shop.create_time
     *
     * @param createTime the value for public.award_shop.create_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.award_shop.update_time
     *
     * @return the value of public.award_shop.update_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.award_shop.update_time
     *
     * @param updateTime the value for public.award_shop.update_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.award_shop.starts
     *
     * @return the value of public.award_shop.starts
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Integer getStarts() {
        return starts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.award_shop.starts
     *
     * @param starts the value for public.award_shop.starts
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setStarts(Integer starts) {
        this.starts = starts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.award_shop.version
     *
     * @return the value of public.award_shop.version
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.award_shop.version
     *
     * @param version the value for public.award_shop.version
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}