package org.capten.live.model;

public class Config {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.config.id
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Object id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.config.uid
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Object uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.config.top_bg_img
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private String topBgImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.config.top_bg_icon
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private String topBgIcon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.config.id
     *
     * @return the value of public.config.id
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Object getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.config.id
     *
     * @param id the value for public.config.id
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setId(Object id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.config.uid
     *
     * @return the value of public.config.uid
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Object getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.config.uid
     *
     * @param uid the value for public.config.uid
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setUid(Object uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.config.top_bg_img
     *
     * @return the value of public.config.top_bg_img
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public String getTopBgImg() {
        return topBgImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.config.top_bg_img
     *
     * @param topBgImg the value for public.config.top_bg_img
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setTopBgImg(String topBgImg) {
        this.topBgImg = topBgImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.config.top_bg_icon
     *
     * @return the value of public.config.top_bg_icon
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public String getTopBgIcon() {
        return topBgIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.config.top_bg_icon
     *
     * @param topBgIcon the value for public.config.top_bg_icon
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setTopBgIcon(String topBgIcon) {
        this.topBgIcon = topBgIcon;
    }

    @Override
    public String toString() {
        return "Config{" +
                "id=" + id +
                ", uid=" + uid +
                ", topBgImg='" + topBgImg + '\'' +
                ", topBgIcon='" + topBgIcon + '\'' +
                '}';
    }
}