package org.capten.live.model;

import java.util.ArrayList;
import java.util.List;

public class ConfigExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.config
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.config
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.config
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.config
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public ConfigExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.config
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.config
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.config
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.config
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.config
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.config
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.config
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.config
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.config
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.config
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.config
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Object value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Object value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Object value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Object value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Object value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Object value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Object> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Object> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Object value1, Object value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Object value1, Object value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(Object value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(Object value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(Object value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Object value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(Object value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(Object value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<Object> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<Object> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(Object value1, Object value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(Object value1, Object value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andTopBgImgIsNull() {
            addCriterion("top_bg_img is null");
            return (Criteria) this;
        }

        public Criteria andTopBgImgIsNotNull() {
            addCriterion("top_bg_img is not null");
            return (Criteria) this;
        }

        public Criteria andTopBgImgEqualTo(String value) {
            addCriterion("top_bg_img =", value, "topBgImg");
            return (Criteria) this;
        }

        public Criteria andTopBgImgNotEqualTo(String value) {
            addCriterion("top_bg_img <>", value, "topBgImg");
            return (Criteria) this;
        }

        public Criteria andTopBgImgGreaterThan(String value) {
            addCriterion("top_bg_img >", value, "topBgImg");
            return (Criteria) this;
        }

        public Criteria andTopBgImgGreaterThanOrEqualTo(String value) {
            addCriterion("top_bg_img >=", value, "topBgImg");
            return (Criteria) this;
        }

        public Criteria andTopBgImgLessThan(String value) {
            addCriterion("top_bg_img <", value, "topBgImg");
            return (Criteria) this;
        }

        public Criteria andTopBgImgLessThanOrEqualTo(String value) {
            addCriterion("top_bg_img <=", value, "topBgImg");
            return (Criteria) this;
        }

        public Criteria andTopBgImgLike(String value) {
            addCriterion("top_bg_img like", value, "topBgImg");
            return (Criteria) this;
        }

        public Criteria andTopBgImgNotLike(String value) {
            addCriterion("top_bg_img not like", value, "topBgImg");
            return (Criteria) this;
        }

        public Criteria andTopBgImgIn(List<String> values) {
            addCriterion("top_bg_img in", values, "topBgImg");
            return (Criteria) this;
        }

        public Criteria andTopBgImgNotIn(List<String> values) {
            addCriterion("top_bg_img not in", values, "topBgImg");
            return (Criteria) this;
        }

        public Criteria andTopBgImgBetween(String value1, String value2) {
            addCriterion("top_bg_img between", value1, value2, "topBgImg");
            return (Criteria) this;
        }

        public Criteria andTopBgImgNotBetween(String value1, String value2) {
            addCriterion("top_bg_img not between", value1, value2, "topBgImg");
            return (Criteria) this;
        }

        public Criteria andTopBgIconIsNull() {
            addCriterion("top_bg_icon is null");
            return (Criteria) this;
        }

        public Criteria andTopBgIconIsNotNull() {
            addCriterion("top_bg_icon is not null");
            return (Criteria) this;
        }

        public Criteria andTopBgIconEqualTo(String value) {
            addCriterion("top_bg_icon =", value, "topBgIcon");
            return (Criteria) this;
        }

        public Criteria andTopBgIconNotEqualTo(String value) {
            addCriterion("top_bg_icon <>", value, "topBgIcon");
            return (Criteria) this;
        }

        public Criteria andTopBgIconGreaterThan(String value) {
            addCriterion("top_bg_icon >", value, "topBgIcon");
            return (Criteria) this;
        }

        public Criteria andTopBgIconGreaterThanOrEqualTo(String value) {
            addCriterion("top_bg_icon >=", value, "topBgIcon");
            return (Criteria) this;
        }

        public Criteria andTopBgIconLessThan(String value) {
            addCriterion("top_bg_icon <", value, "topBgIcon");
            return (Criteria) this;
        }

        public Criteria andTopBgIconLessThanOrEqualTo(String value) {
            addCriterion("top_bg_icon <=", value, "topBgIcon");
            return (Criteria) this;
        }

        public Criteria andTopBgIconLike(String value) {
            addCriterion("top_bg_icon like", value, "topBgIcon");
            return (Criteria) this;
        }

        public Criteria andTopBgIconNotLike(String value) {
            addCriterion("top_bg_icon not like", value, "topBgIcon");
            return (Criteria) this;
        }

        public Criteria andTopBgIconIn(List<String> values) {
            addCriterion("top_bg_icon in", values, "topBgIcon");
            return (Criteria) this;
        }

        public Criteria andTopBgIconNotIn(List<String> values) {
            addCriterion("top_bg_icon not in", values, "topBgIcon");
            return (Criteria) this;
        }

        public Criteria andTopBgIconBetween(String value1, String value2) {
            addCriterion("top_bg_icon between", value1, value2, "topBgIcon");
            return (Criteria) this;
        }

        public Criteria andTopBgIconNotBetween(String value1, String value2) {
            addCriterion("top_bg_icon not between", value1, value2, "topBgIcon");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.config
     *
     * @mbg.generated do_not_delete_during_merge Wed Jan 22 22:27:35 CST 2025
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.config
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}