package org.capten.live.model;

import java.util.Date;

public class ExchangeRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.exchange_record.id
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Object id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.exchange_record.as_id
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Object asId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.exchange_record.user_id
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Object userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.exchange_record.create_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.exchange_record.update_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.exchange_record.is_delete
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.exchange_record.stars
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Integer stars;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.exchange_record.as_name
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private String asName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.exchange_record.as_cover_url
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private String asCoverUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.exchange_record.as_introduce
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private String asIntroduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.exchange_record.version
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.exchange_record.id
     *
     * @return the value of public.exchange_record.id
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Object getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.exchange_record.id
     *
     * @param id the value for public.exchange_record.id
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setId(Object id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.exchange_record.as_id
     *
     * @return the value of public.exchange_record.as_id
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Object getAsId() {
        return asId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.exchange_record.as_id
     *
     * @param asId the value for public.exchange_record.as_id
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setAsId(Object asId) {
        this.asId = asId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.exchange_record.user_id
     *
     * @return the value of public.exchange_record.user_id
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Object getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.exchange_record.user_id
     *
     * @param userId the value for public.exchange_record.user_id
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setUserId(Object userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.exchange_record.create_time
     *
     * @return the value of public.exchange_record.create_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.exchange_record.create_time
     *
     * @param createTime the value for public.exchange_record.create_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.exchange_record.update_time
     *
     * @return the value of public.exchange_record.update_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.exchange_record.update_time
     *
     * @param updateTime the value for public.exchange_record.update_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.exchange_record.is_delete
     *
     * @return the value of public.exchange_record.is_delete
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.exchange_record.is_delete
     *
     * @param isDelete the value for public.exchange_record.is_delete
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.exchange_record.stars
     *
     * @return the value of public.exchange_record.stars
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Integer getStars() {
        return stars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.exchange_record.stars
     *
     * @param stars the value for public.exchange_record.stars
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setStars(Integer stars) {
        this.stars = stars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.exchange_record.as_name
     *
     * @return the value of public.exchange_record.as_name
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public String getAsName() {
        return asName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.exchange_record.as_name
     *
     * @param asName the value for public.exchange_record.as_name
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setAsName(String asName) {
        this.asName = asName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.exchange_record.as_cover_url
     *
     * @return the value of public.exchange_record.as_cover_url
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public String getAsCoverUrl() {
        return asCoverUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.exchange_record.as_cover_url
     *
     * @param asCoverUrl the value for public.exchange_record.as_cover_url
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setAsCoverUrl(String asCoverUrl) {
        this.asCoverUrl = asCoverUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.exchange_record.as_introduce
     *
     * @return the value of public.exchange_record.as_introduce
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public String getAsIntroduce() {
        return asIntroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.exchange_record.as_introduce
     *
     * @param asIntroduce the value for public.exchange_record.as_introduce
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setAsIntroduce(String asIntroduce) {
        this.asIntroduce = asIntroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.exchange_record.version
     *
     * @return the value of public.exchange_record.version
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.exchange_record.version
     *
     * @param version the value for public.exchange_record.version
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}