package org.capten.live.model;

import java.math.BigDecimal;
import java.util.Date;

public class Modules {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.modules.id
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Object id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.modules.pid
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Object pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.modules.last_id
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Object lastId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.modules.name
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.modules.introduce
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private String introduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.modules.is_finish
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Boolean isFinish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.modules.create_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.modules.update_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.modules.is_delete
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.modules.version
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.modules.stars
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private BigDecimal stars;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.modules.belonging_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Date belongingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.modules.start_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.modules.modueles_type
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Integer moduelesType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.modules.id
     *
     * @return the value of public.modules.id
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Object getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.modules.id
     *
     * @param id the value for public.modules.id
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setId(Object id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.modules.pid
     *
     * @return the value of public.modules.pid
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Object getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.modules.pid
     *
     * @param pid the value for public.modules.pid
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setPid(Object pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.modules.last_id
     *
     * @return the value of public.modules.last_id
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Object getLastId() {
        return lastId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.modules.last_id
     *
     * @param lastId the value for public.modules.last_id
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setLastId(Object lastId) {
        this.lastId = lastId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.modules.name
     *
     * @return the value of public.modules.name
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.modules.name
     *
     * @param name the value for public.modules.name
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.modules.introduce
     *
     * @return the value of public.modules.introduce
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.modules.introduce
     *
     * @param introduce the value for public.modules.introduce
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.modules.is_finish
     *
     * @return the value of public.modules.is_finish
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Boolean getIsFinish() {
        return isFinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.modules.is_finish
     *
     * @param isFinish the value for public.modules.is_finish
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setIsFinish(Boolean isFinish) {
        this.isFinish = isFinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.modules.create_time
     *
     * @return the value of public.modules.create_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.modules.create_time
     *
     * @param createTime the value for public.modules.create_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.modules.update_time
     *
     * @return the value of public.modules.update_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.modules.update_time
     *
     * @param updateTime the value for public.modules.update_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.modules.is_delete
     *
     * @return the value of public.modules.is_delete
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.modules.is_delete
     *
     * @param isDelete the value for public.modules.is_delete
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.modules.version
     *
     * @return the value of public.modules.version
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.modules.version
     *
     * @param version the value for public.modules.version
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.modules.stars
     *
     * @return the value of public.modules.stars
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public BigDecimal getStars() {
        return stars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.modules.stars
     *
     * @param stars the value for public.modules.stars
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setStars(BigDecimal stars) {
        this.stars = stars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.modules.belonging_time
     *
     * @return the value of public.modules.belonging_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Date getBelongingTime() {
        return belongingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.modules.belonging_time
     *
     * @param belongingTime the value for public.modules.belonging_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setBelongingTime(Date belongingTime) {
        this.belongingTime = belongingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.modules.start_time
     *
     * @return the value of public.modules.start_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.modules.start_time
     *
     * @param startTime the value for public.modules.start_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.modules.modueles_type
     *
     * @return the value of public.modules.modueles_type
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Integer getModuelesType() {
        return moduelesType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.modules.modueles_type
     *
     * @param moduelesType the value for public.modules.modueles_type
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setModuelesType(Integer moduelesType) {
        this.moduelesType = moduelesType;
    }
}