package org.capten.live.model;

import java.util.Date;

public class MoneyPayRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.money_pay_record.id
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Object id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.money_pay_record.create_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.money_pay_record.update_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.money_pay_record.is_delete
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.money_pay_record.version
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.money_pay_record.tag_ids
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private String tagIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.money_pay_record.way
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Integer way;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.money_pay_record.user_id
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Object userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.money_pay_record.name
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.money_pay_record.remark
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.money_pay_record.id
     *
     * @return the value of public.money_pay_record.id
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Object getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.money_pay_record.id
     *
     * @param id the value for public.money_pay_record.id
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setId(Object id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.money_pay_record.create_time
     *
     * @return the value of public.money_pay_record.create_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.money_pay_record.create_time
     *
     * @param createTime the value for public.money_pay_record.create_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.money_pay_record.update_time
     *
     * @return the value of public.money_pay_record.update_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.money_pay_record.update_time
     *
     * @param updateTime the value for public.money_pay_record.update_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.money_pay_record.is_delete
     *
     * @return the value of public.money_pay_record.is_delete
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.money_pay_record.is_delete
     *
     * @param isDelete the value for public.money_pay_record.is_delete
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.money_pay_record.version
     *
     * @return the value of public.money_pay_record.version
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.money_pay_record.version
     *
     * @param version the value for public.money_pay_record.version
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.money_pay_record.tag_ids
     *
     * @return the value of public.money_pay_record.tag_ids
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public String getTagIds() {
        return tagIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.money_pay_record.tag_ids
     *
     * @param tagIds the value for public.money_pay_record.tag_ids
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setTagIds(String tagIds) {
        this.tagIds = tagIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.money_pay_record.way
     *
     * @return the value of public.money_pay_record.way
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Integer getWay() {
        return way;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.money_pay_record.way
     *
     * @param way the value for public.money_pay_record.way
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setWay(Integer way) {
        this.way = way;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.money_pay_record.user_id
     *
     * @return the value of public.money_pay_record.user_id
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Object getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.money_pay_record.user_id
     *
     * @param userId the value for public.money_pay_record.user_id
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setUserId(Object userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.money_pay_record.name
     *
     * @return the value of public.money_pay_record.name
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.money_pay_record.name
     *
     * @param name the value for public.money_pay_record.name
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.money_pay_record.remark
     *
     * @return the value of public.money_pay_record.remark
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.money_pay_record.remark
     *
     * @param remark the value for public.money_pay_record.remark
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}