package org.capten.live.model;

import java.math.BigDecimal;
import java.util.Date;

public class Projects {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.projects.id
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Object id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.projects.uid
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Object uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.projects.name
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.projects.introduce
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private String introduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.projects.is_finish
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Boolean isFinish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.projects.is_delete
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.projects.create_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.projects.update_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.projects.version
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.projects.stars
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private BigDecimal stars;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.projects.belonging_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Date belongingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.projects.start_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Date startTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.projects.id
     *
     * @return the value of public.projects.id
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Object getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.projects.id
     *
     * @param id the value for public.projects.id
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setId(Object id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.projects.uid
     *
     * @return the value of public.projects.uid
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Object getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.projects.uid
     *
     * @param uid the value for public.projects.uid
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setUid(Object uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.projects.name
     *
     * @return the value of public.projects.name
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.projects.name
     *
     * @param name the value for public.projects.name
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.projects.introduce
     *
     * @return the value of public.projects.introduce
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.projects.introduce
     *
     * @param introduce the value for public.projects.introduce
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.projects.is_finish
     *
     * @return the value of public.projects.is_finish
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Boolean getIsFinish() {
        return isFinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.projects.is_finish
     *
     * @param isFinish the value for public.projects.is_finish
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setIsFinish(Boolean isFinish) {
        this.isFinish = isFinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.projects.is_delete
     *
     * @return the value of public.projects.is_delete
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.projects.is_delete
     *
     * @param isDelete the value for public.projects.is_delete
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.projects.create_time
     *
     * @return the value of public.projects.create_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.projects.create_time
     *
     * @param createTime the value for public.projects.create_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.projects.update_time
     *
     * @return the value of public.projects.update_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.projects.update_time
     *
     * @param updateTime the value for public.projects.update_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.projects.version
     *
     * @return the value of public.projects.version
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.projects.version
     *
     * @param version the value for public.projects.version
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.projects.stars
     *
     * @return the value of public.projects.stars
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public BigDecimal getStars() {
        return stars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.projects.stars
     *
     * @param stars the value for public.projects.stars
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setStars(BigDecimal stars) {
        this.stars = stars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.projects.belonging_time
     *
     * @return the value of public.projects.belonging_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Date getBelongingTime() {
        return belongingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.projects.belonging_time
     *
     * @param belongingTime the value for public.projects.belonging_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setBelongingTime(Date belongingTime) {
        this.belongingTime = belongingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.projects.start_time
     *
     * @return the value of public.projects.start_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.projects.start_time
     *
     * @param startTime the value for public.projects.start_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
}