package org.capten.live.model;

import java.util.Date;

public class ReviewType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.review_type.id
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Object id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.review_type.user_id
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Object userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.review_type.name
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.review_type.sort
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.review_type.is_delete
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.review_type.create_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.review_type.update_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.review_type.version
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.review_type.id
     *
     * @return the value of public.review_type.id
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Object getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.review_type.id
     *
     * @param id the value for public.review_type.id
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setId(Object id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.review_type.user_id
     *
     * @return the value of public.review_type.user_id
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Object getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.review_type.user_id
     *
     * @param userId the value for public.review_type.user_id
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setUserId(Object userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.review_type.name
     *
     * @return the value of public.review_type.name
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.review_type.name
     *
     * @param name the value for public.review_type.name
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.review_type.sort
     *
     * @return the value of public.review_type.sort
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.review_type.sort
     *
     * @param sort the value for public.review_type.sort
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.review_type.is_delete
     *
     * @return the value of public.review_type.is_delete
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.review_type.is_delete
     *
     * @param isDelete the value for public.review_type.is_delete
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.review_type.create_time
     *
     * @return the value of public.review_type.create_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.review_type.create_time
     *
     * @param createTime the value for public.review_type.create_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.review_type.update_time
     *
     * @return the value of public.review_type.update_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.review_type.update_time
     *
     * @param updateTime the value for public.review_type.update_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.review_type.version
     *
     * @return the value of public.review_type.version
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.review_type.version
     *
     * @param version the value for public.review_type.version
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}