package org.capten.live.model;

import java.math.BigDecimal;
import java.util.Date;

public class RuntimeTask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.runtime_task.id
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Object id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.runtime_task.name
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.runtime_task.remark
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.runtime_task.stars
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private BigDecimal stars;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.runtime_task.belonging_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Date belongingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.runtime_task.is_finish
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Boolean isFinish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.runtime_task.create_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.runtime_task.update_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.runtime_task.version
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.runtime_task.uid
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Object uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.runtime_task.is_delete
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.runtime_task.create_way
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Integer createWay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.runtime_task.external_id
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private String externalId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.runtime_task.id
     *
     * @return the value of public.runtime_task.id
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Object getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.runtime_task.id
     *
     * @param id the value for public.runtime_task.id
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setId(Object id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.runtime_task.name
     *
     * @return the value of public.runtime_task.name
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.runtime_task.name
     *
     * @param name the value for public.runtime_task.name
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.runtime_task.remark
     *
     * @return the value of public.runtime_task.remark
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.runtime_task.remark
     *
     * @param remark the value for public.runtime_task.remark
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.runtime_task.stars
     *
     * @return the value of public.runtime_task.stars
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public BigDecimal getStars() {
        return stars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.runtime_task.stars
     *
     * @param stars the value for public.runtime_task.stars
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setStars(BigDecimal stars) {
        this.stars = stars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.runtime_task.belonging_time
     *
     * @return the value of public.runtime_task.belonging_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Date getBelongingTime() {
        return belongingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.runtime_task.belonging_time
     *
     * @param belongingTime the value for public.runtime_task.belonging_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setBelongingTime(Date belongingTime) {
        this.belongingTime = belongingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.runtime_task.is_finish
     *
     * @return the value of public.runtime_task.is_finish
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Boolean getIsFinish() {
        return isFinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.runtime_task.is_finish
     *
     * @param isFinish the value for public.runtime_task.is_finish
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setIsFinish(Boolean isFinish) {
        this.isFinish = isFinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.runtime_task.create_time
     *
     * @return the value of public.runtime_task.create_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.runtime_task.create_time
     *
     * @param createTime the value for public.runtime_task.create_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.runtime_task.update_time
     *
     * @return the value of public.runtime_task.update_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.runtime_task.update_time
     *
     * @param updateTime the value for public.runtime_task.update_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.runtime_task.version
     *
     * @return the value of public.runtime_task.version
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.runtime_task.version
     *
     * @param version the value for public.runtime_task.version
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.runtime_task.uid
     *
     * @return the value of public.runtime_task.uid
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Object getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.runtime_task.uid
     *
     * @param uid the value for public.runtime_task.uid
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setUid(Object uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.runtime_task.is_delete
     *
     * @return the value of public.runtime_task.is_delete
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.runtime_task.is_delete
     *
     * @param isDelete the value for public.runtime_task.is_delete
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.runtime_task.create_way
     *
     * @return the value of public.runtime_task.create_way
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Integer getCreateWay() {
        return createWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.runtime_task.create_way
     *
     * @param createWay the value for public.runtime_task.create_way
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setCreateWay(Integer createWay) {
        this.createWay = createWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.runtime_task.external_id
     *
     * @return the value of public.runtime_task.external_id
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public String getExternalId() {
        return externalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.runtime_task.external_id
     *
     * @param externalId the value for public.runtime_task.external_id
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setExternalId(String externalId) {
        this.externalId = externalId;
    }
}