package org.capten.live.model;

import java.util.Date;

public class RuntimeTaskEngine {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.runtime_task_engine.id
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Object id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.runtime_task_engine.uid
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Object uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.runtime_task_engine.is_delete
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Date isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.runtime_task_engine.rtt_id
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Object rttId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.runtime_task_engine.create_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.runtime_task_engine.update_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.runtime_task_engine.version
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.runtime_task_engine.belonging_time_way
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Integer belongingTimeWay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.runtime_task_engine.belonging_time_str
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private String belongingTimeStr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.runtime_task_engine.id
     *
     * @return the value of public.runtime_task_engine.id
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Object getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.runtime_task_engine.id
     *
     * @param id the value for public.runtime_task_engine.id
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setId(Object id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.runtime_task_engine.uid
     *
     * @return the value of public.runtime_task_engine.uid
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Object getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.runtime_task_engine.uid
     *
     * @param uid the value for public.runtime_task_engine.uid
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setUid(Object uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.runtime_task_engine.is_delete
     *
     * @return the value of public.runtime_task_engine.is_delete
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Date getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.runtime_task_engine.is_delete
     *
     * @param isDelete the value for public.runtime_task_engine.is_delete
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setIsDelete(Date isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.runtime_task_engine.rtt_id
     *
     * @return the value of public.runtime_task_engine.rtt_id
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Object getRttId() {
        return rttId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.runtime_task_engine.rtt_id
     *
     * @param rttId the value for public.runtime_task_engine.rtt_id
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setRttId(Object rttId) {
        this.rttId = rttId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.runtime_task_engine.create_time
     *
     * @return the value of public.runtime_task_engine.create_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.runtime_task_engine.create_time
     *
     * @param createTime the value for public.runtime_task_engine.create_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.runtime_task_engine.update_time
     *
     * @return the value of public.runtime_task_engine.update_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.runtime_task_engine.update_time
     *
     * @param updateTime the value for public.runtime_task_engine.update_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.runtime_task_engine.version
     *
     * @return the value of public.runtime_task_engine.version
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.runtime_task_engine.version
     *
     * @param version the value for public.runtime_task_engine.version
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.runtime_task_engine.belonging_time_way
     *
     * @return the value of public.runtime_task_engine.belonging_time_way
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Integer getBelongingTimeWay() {
        return belongingTimeWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.runtime_task_engine.belonging_time_way
     *
     * @param belongingTimeWay the value for public.runtime_task_engine.belonging_time_way
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setBelongingTimeWay(Integer belongingTimeWay) {
        this.belongingTimeWay = belongingTimeWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.runtime_task_engine.belonging_time_str
     *
     * @return the value of public.runtime_task_engine.belonging_time_str
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public String getBelongingTimeStr() {
        return belongingTimeStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.runtime_task_engine.belonging_time_str
     *
     * @param belongingTimeStr the value for public.runtime_task_engine.belonging_time_str
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setBelongingTimeStr(String belongingTimeStr) {
        this.belongingTimeStr = belongingTimeStr;
    }
}