package org.capten.live.model;

import java.math.BigDecimal;
import java.util.Date;

public class RuntimeTaskTemplate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.runtime_task_template.id
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Object id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.runtime_task_template.uid
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Object uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.runtime_task_template.name
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.runtime_task_template.version
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.runtime_task_template.create_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.runtime_task_template.update_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.runtime_task_template.remark
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.runtime_task_template.stars
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private BigDecimal stars;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.runtime_task_template.belonging_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private String belongingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.runtime_task_template.is_delete
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Boolean isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.runtime_task_template.id
     *
     * @return the value of public.runtime_task_template.id
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Object getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.runtime_task_template.id
     *
     * @param id the value for public.runtime_task_template.id
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setId(Object id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.runtime_task_template.uid
     *
     * @return the value of public.runtime_task_template.uid
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Object getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.runtime_task_template.uid
     *
     * @param uid the value for public.runtime_task_template.uid
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setUid(Object uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.runtime_task_template.name
     *
     * @return the value of public.runtime_task_template.name
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.runtime_task_template.name
     *
     * @param name the value for public.runtime_task_template.name
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.runtime_task_template.version
     *
     * @return the value of public.runtime_task_template.version
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.runtime_task_template.version
     *
     * @param version the value for public.runtime_task_template.version
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.runtime_task_template.create_time
     *
     * @return the value of public.runtime_task_template.create_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.runtime_task_template.create_time
     *
     * @param createTime the value for public.runtime_task_template.create_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.runtime_task_template.update_time
     *
     * @return the value of public.runtime_task_template.update_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.runtime_task_template.update_time
     *
     * @param updateTime the value for public.runtime_task_template.update_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.runtime_task_template.remark
     *
     * @return the value of public.runtime_task_template.remark
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.runtime_task_template.remark
     *
     * @param remark the value for public.runtime_task_template.remark
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.runtime_task_template.stars
     *
     * @return the value of public.runtime_task_template.stars
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public BigDecimal getStars() {
        return stars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.runtime_task_template.stars
     *
     * @param stars the value for public.runtime_task_template.stars
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setStars(BigDecimal stars) {
        this.stars = stars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.runtime_task_template.belonging_time
     *
     * @return the value of public.runtime_task_template.belonging_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public String getBelongingTime() {
        return belongingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.runtime_task_template.belonging_time
     *
     * @param belongingTime the value for public.runtime_task_template.belonging_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setBelongingTime(String belongingTime) {
        this.belongingTime = belongingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.runtime_task_template.is_delete
     *
     * @return the value of public.runtime_task_template.is_delete
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.runtime_task_template.is_delete
     *
     * @param isDelete the value for public.runtime_task_template.is_delete
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }
}