package org.capten.live.model;

import java.math.BigDecimal;
import java.util.Date;

public class Tasks {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tasks.id
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Object id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tasks.user_id
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Object userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tasks.type
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Short type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tasks.content
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tasks.is_finished
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Boolean isFinished;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tasks.create_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tasks.update_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tasks.finish_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Date finishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tasks.remark
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tasks.starts
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private BigDecimal starts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tasks.experience
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Integer experience;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tasks.version
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tasks.id
     *
     * @return the value of public.tasks.id
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Object getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tasks.id
     *
     * @param id the value for public.tasks.id
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setId(Object id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tasks.user_id
     *
     * @return the value of public.tasks.user_id
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Object getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tasks.user_id
     *
     * @param userId the value for public.tasks.user_id
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setUserId(Object userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tasks.type
     *
     * @return the value of public.tasks.type
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tasks.type
     *
     * @param type the value for public.tasks.type
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tasks.content
     *
     * @return the value of public.tasks.content
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tasks.content
     *
     * @param content the value for public.tasks.content
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tasks.is_finished
     *
     * @return the value of public.tasks.is_finished
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Boolean getIsFinished() {
        return isFinished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tasks.is_finished
     *
     * @param isFinished the value for public.tasks.is_finished
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setIsFinished(Boolean isFinished) {
        this.isFinished = isFinished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tasks.create_time
     *
     * @return the value of public.tasks.create_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tasks.create_time
     *
     * @param createTime the value for public.tasks.create_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tasks.update_time
     *
     * @return the value of public.tasks.update_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tasks.update_time
     *
     * @param updateTime the value for public.tasks.update_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tasks.finish_time
     *
     * @return the value of public.tasks.finish_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tasks.finish_time
     *
     * @param finishTime the value for public.tasks.finish_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tasks.remark
     *
     * @return the value of public.tasks.remark
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tasks.remark
     *
     * @param remark the value for public.tasks.remark
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tasks.starts
     *
     * @return the value of public.tasks.starts
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public BigDecimal getStarts() {
        return starts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tasks.starts
     *
     * @param starts the value for public.tasks.starts
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setStarts(BigDecimal starts) {
        this.starts = starts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tasks.experience
     *
     * @return the value of public.tasks.experience
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Integer getExperience() {
        return experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tasks.experience
     *
     * @param experience the value for public.tasks.experience
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setExperience(Integer experience) {
        this.experience = experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tasks.version
     *
     * @return the value of public.tasks.version
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tasks.version
     *
     * @param version the value for public.tasks.version
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}