package org.capten.live.model;

import java.util.Date;

public class TasksIndex {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tasks_index.id
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tasks_index.t_id
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Object tId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tasks_index.starts
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Integer starts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tasks_index.content
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tasks_index.create_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tasks_index.update_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tasks_index.is_delete
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tasks_index.is_finish
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Boolean isFinish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tasks_index.finish_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Date finishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tasks_index.experience
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Integer experience;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tasks_index.version
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tasks_index.id
     *
     * @return the value of public.tasks_index.id
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tasks_index.id
     *
     * @param id the value for public.tasks_index.id
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tasks_index.t_id
     *
     * @return the value of public.tasks_index.t_id
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Object gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tasks_index.t_id
     *
     * @param tId the value for public.tasks_index.t_id
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void settId(Object tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tasks_index.starts
     *
     * @return the value of public.tasks_index.starts
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Integer getStarts() {
        return starts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tasks_index.starts
     *
     * @param starts the value for public.tasks_index.starts
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setStarts(Integer starts) {
        this.starts = starts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tasks_index.content
     *
     * @return the value of public.tasks_index.content
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tasks_index.content
     *
     * @param content the value for public.tasks_index.content
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tasks_index.create_time
     *
     * @return the value of public.tasks_index.create_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tasks_index.create_time
     *
     * @param createTime the value for public.tasks_index.create_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tasks_index.update_time
     *
     * @return the value of public.tasks_index.update_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tasks_index.update_time
     *
     * @param updateTime the value for public.tasks_index.update_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tasks_index.is_delete
     *
     * @return the value of public.tasks_index.is_delete
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tasks_index.is_delete
     *
     * @param isDelete the value for public.tasks_index.is_delete
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tasks_index.is_finish
     *
     * @return the value of public.tasks_index.is_finish
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Boolean getIsFinish() {
        return isFinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tasks_index.is_finish
     *
     * @param isFinish the value for public.tasks_index.is_finish
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setIsFinish(Boolean isFinish) {
        this.isFinish = isFinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tasks_index.finish_time
     *
     * @return the value of public.tasks_index.finish_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tasks_index.finish_time
     *
     * @param finishTime the value for public.tasks_index.finish_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tasks_index.experience
     *
     * @return the value of public.tasks_index.experience
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Integer getExperience() {
        return experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tasks_index.experience
     *
     * @param experience the value for public.tasks_index.experience
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setExperience(Integer experience) {
        this.experience = experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tasks_index.version
     *
     * @return the value of public.tasks_index.version
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tasks_index.version
     *
     * @param version the value for public.tasks_index.version
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}