package org.capten.live.model;

import java.util.Date;

public class TasksComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tasks_comment.id
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Object id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tasks_comment.user_id
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Object userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tasks_comment.username
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tasks_comment.comment
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tasks_comment.create_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tasks_comment.update_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tasks_comment.t_id
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Object tId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tasks_comment.file_type
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private String fileType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tasks_comment.file_url
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private String fileUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tasks_comment.is_delete
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tasks_comment.version
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tasks_comment.id
     *
     * @return the value of public.tasks_comment.id
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Object getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tasks_comment.id
     *
     * @param id the value for public.tasks_comment.id
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setId(Object id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tasks_comment.user_id
     *
     * @return the value of public.tasks_comment.user_id
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Object getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tasks_comment.user_id
     *
     * @param userId the value for public.tasks_comment.user_id
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setUserId(Object userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tasks_comment.username
     *
     * @return the value of public.tasks_comment.username
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tasks_comment.username
     *
     * @param username the value for public.tasks_comment.username
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tasks_comment.comment
     *
     * @return the value of public.tasks_comment.comment
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tasks_comment.comment
     *
     * @param comment the value for public.tasks_comment.comment
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tasks_comment.create_time
     *
     * @return the value of public.tasks_comment.create_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tasks_comment.create_time
     *
     * @param createTime the value for public.tasks_comment.create_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tasks_comment.update_time
     *
     * @return the value of public.tasks_comment.update_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tasks_comment.update_time
     *
     * @param updateTime the value for public.tasks_comment.update_time
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tasks_comment.t_id
     *
     * @return the value of public.tasks_comment.t_id
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Object gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tasks_comment.t_id
     *
     * @param tId the value for public.tasks_comment.t_id
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void settId(Object tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tasks_comment.file_type
     *
     * @return the value of public.tasks_comment.file_type
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tasks_comment.file_type
     *
     * @param fileType the value for public.tasks_comment.file_type
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tasks_comment.file_url
     *
     * @return the value of public.tasks_comment.file_url
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tasks_comment.file_url
     *
     * @param fileUrl the value for public.tasks_comment.file_url
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tasks_comment.is_delete
     *
     * @return the value of public.tasks_comment.is_delete
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tasks_comment.is_delete
     *
     * @param isDelete the value for public.tasks_comment.is_delete
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tasks_comment.version
     *
     * @return the value of public.tasks_comment.version
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tasks_comment.version
     *
     * @param version the value for public.tasks_comment.version
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}