package org.capten.live.model;

import java.math.BigDecimal;
import java.util.Date;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.id
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Object id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.username
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.password
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.money
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private BigDecimal money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.birthday
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.stars
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private BigDecimal stars;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.used_stars
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private BigDecimal usedStars;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.create_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.update_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.is_delete
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.avatar
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.level
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.experience
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Long experience;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.version
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.save_money
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    private BigDecimal saveMoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.id
     *
     * @return the value of public.users.id
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Object getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.id
     *
     * @param id the value for public.users.id
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setId(Object id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.username
     *
     * @return the value of public.users.username
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.username
     *
     * @param username the value for public.users.username
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.password
     *
     * @return the value of public.users.password
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.password
     *
     * @param password the value for public.users.password
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.money
     *
     * @return the value of public.users.money
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.money
     *
     * @param money the value for public.users.money
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.birthday
     *
     * @return the value of public.users.birthday
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.birthday
     *
     * @param birthday the value for public.users.birthday
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.stars
     *
     * @return the value of public.users.stars
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public BigDecimal getStars() {
        return stars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.stars
     *
     * @param stars the value for public.users.stars
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setStars(BigDecimal stars) {
        this.stars = stars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.used_stars
     *
     * @return the value of public.users.used_stars
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public BigDecimal getUsedStars() {
        return usedStars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.used_stars
     *
     * @param usedStars the value for public.users.used_stars
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setUsedStars(BigDecimal usedStars) {
        this.usedStars = usedStars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.create_time
     *
     * @return the value of public.users.create_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.create_time
     *
     * @param createTime the value for public.users.create_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.update_time
     *
     * @return the value of public.users.update_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.update_time
     *
     * @param updateTime the value for public.users.update_time
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.is_delete
     *
     * @return the value of public.users.is_delete
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.is_delete
     *
     * @param isDelete the value for public.users.is_delete
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.avatar
     *
     * @return the value of public.users.avatar
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.avatar
     *
     * @param avatar the value for public.users.avatar
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.level
     *
     * @return the value of public.users.level
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.level
     *
     * @param level the value for public.users.level
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.experience
     *
     * @return the value of public.users.experience
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Long getExperience() {
        return experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.experience
     *
     * @param experience the value for public.users.experience
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setExperience(Long experience) {
        this.experience = experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.version
     *
     * @return the value of public.users.version
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.version
     *
     * @param version the value for public.users.version
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.save_money
     *
     * @return the value of public.users.save_money
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public BigDecimal getSaveMoney() {
        return saveMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.save_money
     *
     * @param saveMoney the value for public.users.save_money
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    public void setSaveMoney(BigDecimal saveMoney) {
        this.saveMoney = saveMoney;
    }
}