
CREATE TABLE "users" (
	"id" UUID NOT NULL UNIQUE,
	"username" VARCHAR(30),
	"password" VARCHAR(32),
	"money" DECIMAL(10,2),
	"birthday" DATE,
	"stars" DECIMAL(10,2),
	"used_stars" DECIMAL(10,2),
	"create_time" TIMESTAMP,
	"update_time" TIMESTAMP,
	"is_delete" BOOLEAN,
	"avatar" VARCHAR(255),
	"level" INTEGER,
	"experience" BIGINT,
	PRIMARY KEY("id")
);


CREATE TABLE "current_status" (
	"id" UUID NOT NULL UNIQUE,
	"user_id" UUID,
	"content" VARCHAR(255),
	"create_time" TIMESTAMP,
	"update_time" TIMESTAMP,
	"is_delete" BOOLEAN,
	PRIMARY KEY("id")
);


CREATE TABLE "final_aim" (
	"id" UUID NOT NULL UNIQUE,
	"user_id" UUID,
	"content" VARCHAR(255),
	"create_time" TIMESTAMP,
	"update_time" TIMESTAMP,
	"is_delete" BOOLEAN,
	"is_finished" BOOLEAN,
	PRIMARY KEY("id")
);


CREATE TABLE "review_type" (
	"id" UUID NOT NULL UNIQUE,
	"user_id" UUID,
	"name" VARCHAR(255),
	"sort" INTEGER DEFAULT 10,
	"is_delete" BOOLEAN,
	"create_time" TIMESTAMP,
	"update_time" TIMESTAMP,
	PRIMARY KEY("id")
);


CREATE TABLE "review_record" (
	"id" UUID NOT NULL UNIQUE,
	"user_id" UUID,
	"rt_id" UUID,
	"is_delete" BOOLEAN,
	"content" TEXT,
	"create_time" TIMESTAMP,
	"update_time" TIMESTAMP,
	PRIMARY KEY("id")
);


CREATE TABLE "review_record_comment" (
	"id" UUID NOT NULL UNIQUE,
	"user_id" UUID,
	"username" VARCHAR(255),
	"comment" TEXT,
	"create_time" TIMESTAMP,
	"update_time" TIMESTAMP,
	"is_delete" BOOLEAN,
	"rr_id" UUID,
	"file_type" VARCHAR(20),
	"file_url" VARCHAR(255),
	PRIMARY KEY("id")
);


CREATE TABLE "tasks" (
	"id" UUID NOT NULL UNIQUE,
	"user_id" UUID,
	"type" SMALLINT,
	"content" VARCHAR(255),
	"is_finished" BOOLEAN,
	"create_time" TIMESTAMP,
	"update_time" TIMESTAMP,
	"finish_time" TIMESTAMP,
	"remark" TEXT,
	"starts" INTEGER,
	"experience" INTEGER,
	PRIMARY KEY("id")
);


CREATE TABLE "tasks_index" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"t_id" UUID,
	"starts" INTEGER,
	"content" VARCHAR(255),
	"create_time" TIMESTAMP,
	"update_time" TIMESTAMP,
	"is_delete" BOOLEAN,
	"is_finish" BOOLEAN,
	"finish_time" TIMESTAMP,
	"experience" INTEGER,
	PRIMARY KEY("id")
);


CREATE TABLE "tasks_comment" (
	"id" UUID NOT NULL UNIQUE,
	"user_id" UUID,
	"username" VARCHAR(255),
	"comment" TEXT,
	"create_time" TIMESTAMP,
	"update_time" TIMESTAMP,
	"t_id" UUID,
	"file_type" VARCHAR(20),
	"file_url" VARCHAR(255),
	"is_delete" BOOLEAN,
	PRIMARY KEY("id")
);


CREATE TABLE "award_shop" (
	"id" UUID NOT NULL UNIQUE,
	"user_id" UUID,
	"name" VARCHAR(255),
	"introduce" TEXT,
	"cover_img" VARCHAR(255),
	"num" INTEGER,
	"is_delete" BOOLEAN,
	"create_time" TIMESTAMP,
	"update_time" TIMESTAMP,
	"starts" INTEGER,
	PRIMARY KEY("id")
);


CREATE TABLE "exchange_record" (
	"id" UUID NOT NULL UNIQUE,
	"as_id" UUID,
	"user_id" UUID,
	"create_time" TIMESTAMP,
	"update_time" TIMESTAMP,
	"is_delete" BOOLEAN,
	"stars" INTEGER,
	"as_name" VARCHAR(255),
	"as_cover_url" VARCHAR(255),
	"as_introduce" TEXT,
	PRIMARY KEY("id")
);


CREATE TABLE "life_list" (
	"id" UUID NOT NULL UNIQUE,
	"user_id" UUID,
	"content" VARCHAR(255),
	"is_delete" BOOLEAN,
	"create_time" TIMESTAMP,
	"update_time" TIMESTAMP,
	"is_finish" BOOLEAN,
	PRIMARY KEY("id")
);