package org.capten.live.mapper;

import java.util.List;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Param;
import org.capten.live.model.AwardShop;
import org.capten.live.model.AwardShopExample;

public interface AwardShopMapper extends BaseMapper<AwardShopExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.award_shop
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    long countByExample(AwardShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.award_shop
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int deleteByExample(AwardShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.award_shop
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int deleteByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.award_shop
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int insert(AwardShop row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.award_shop
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int insertSelective(AwardShop row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.award_shop
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    List<AwardShop> selectByExample(AwardShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.award_shop
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    AwardShop selectByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.award_shop
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int updateByExampleSelective(@Param("row") AwardShop row, @Param("example") AwardShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.award_shop
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int updateByExample(@Param("row") AwardShop row, @Param("example") AwardShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.award_shop
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int updateByPrimaryKeySelective(AwardShop row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.award_shop
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int updateByPrimaryKey(AwardShop row);
}