package org.capten.live.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.capten.live.model.ExpenditureTag;
import org.capten.live.model.ExpenditureTagExample;

public interface ExpenditureTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.expenditure_tag
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    long countByExample(ExpenditureTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.expenditure_tag
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int deleteByExample(ExpenditureTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.expenditure_tag
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int deleteByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.expenditure_tag
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int insert(ExpenditureTag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.expenditure_tag
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int insertSelective(ExpenditureTag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.expenditure_tag
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    List<ExpenditureTag> selectByExample(ExpenditureTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.expenditure_tag
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    ExpenditureTag selectByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.expenditure_tag
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int updateByExampleSelective(@Param("row") ExpenditureTag row, @Param("example") ExpenditureTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.expenditure_tag
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int updateByExample(@Param("row") ExpenditureTag row, @Param("example") ExpenditureTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.expenditure_tag
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int updateByPrimaryKeySelective(ExpenditureTag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.expenditure_tag
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int updateByPrimaryKey(ExpenditureTag row);
}