package org.capten.live.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.capten.live.model.FinalAim;
import org.capten.live.model.FinalAimExample;

public interface FinalAimMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.final_aim
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    long countByExample(FinalAimExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.final_aim
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int deleteByExample(FinalAimExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.final_aim
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int deleteByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.final_aim
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int insert(FinalAim row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.final_aim
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int insertSelective(FinalAim row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.final_aim
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    List<FinalAim> selectByExample(FinalAimExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.final_aim
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    FinalAim selectByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.final_aim
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int updateByExampleSelective(@Param("row") FinalAim row, @Param("example") FinalAimExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.final_aim
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int updateByExample(@Param("row") FinalAim row, @Param("example") FinalAimExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.final_aim
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int updateByPrimaryKeySelective(FinalAim row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.final_aim
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int updateByPrimaryKey(FinalAim row);
}