package org.capten.live.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.capten.live.model.IncomeTag;
import org.capten.live.model.IncomeTagExample;

public interface IncomeTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.income_tag
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    long countByExample(IncomeTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.income_tag
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int deleteByExample(IncomeTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.income_tag
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int deleteByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.income_tag
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int insert(IncomeTag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.income_tag
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int insertSelective(IncomeTag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.income_tag
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    List<IncomeTag> selectByExample(IncomeTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.income_tag
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    IncomeTag selectByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.income_tag
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int updateByExampleSelective(@Param("row") IncomeTag row, @Param("example") IncomeTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.income_tag
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int updateByExample(@Param("row") IncomeTag row, @Param("example") IncomeTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.income_tag
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int updateByPrimaryKeySelective(IncomeTag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.income_tag
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int updateByPrimaryKey(IncomeTag row);
}