package org.capten.live.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.capten.live.model.LifeList;
import org.capten.live.model.LifeListExample;

public interface LifeListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.life_list
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    long countByExample(LifeListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.life_list
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int deleteByExample(LifeListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.life_list
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int deleteByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.life_list
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int insert(LifeList row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.life_list
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int insertSelective(LifeList row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.life_list
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    List<LifeList> selectByExample(LifeListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.life_list
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    LifeList selectByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.life_list
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int updateByExampleSelective(@Param("row") LifeList row, @Param("example") LifeListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.life_list
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int updateByExample(@Param("row") LifeList row, @Param("example") LifeListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.life_list
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int updateByPrimaryKeySelective(LifeList row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.life_list
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int updateByPrimaryKey(LifeList row);
}