package org.capten.live.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.capten.live.model.Modules;
import org.capten.live.model.ModulesExample;

public interface ModulesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.modules
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    long countByExample(ModulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.modules
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int deleteByExample(ModulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.modules
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int deleteByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.modules
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int insert(Modules row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.modules
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int insertSelective(Modules row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.modules
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    List<Modules> selectByExample(ModulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.modules
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    Modules selectByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.modules
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int updateByExampleSelective(@Param("row") Modules row, @Param("example") ModulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.modules
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int updateByExample(@Param("row") Modules row, @Param("example") ModulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.modules
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int updateByPrimaryKeySelective(Modules row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.modules
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int updateByPrimaryKey(Modules row);
}