package org.capten.live.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.capten.live.model.Projects;
import org.capten.live.model.ProjectsExample;

public interface ProjectsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.projects
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    long countByExample(ProjectsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.projects
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int deleteByExample(ProjectsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.projects
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int deleteByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.projects
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int insert(Projects row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.projects
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int insertSelective(Projects row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.projects
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    List<Projects> selectByExample(ProjectsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.projects
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    Projects selectByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.projects
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int updateByExampleSelective(@Param("row") Projects row, @Param("example") ProjectsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.projects
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int updateByExample(@Param("row") Projects row, @Param("example") ProjectsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.projects
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int updateByPrimaryKeySelective(Projects row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.projects
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int updateByPrimaryKey(Projects row);
}