package org.capten.live.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.capten.live.model.ReviewType;
import org.capten.live.model.ReviewTypeExample;

public interface ReviewTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.review_type
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    long countByExample(ReviewTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.review_type
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int deleteByExample(ReviewTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.review_type
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int deleteByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.review_type
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int insert(ReviewType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.review_type
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int insertSelective(ReviewType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.review_type
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    List<ReviewType> selectByExample(ReviewTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.review_type
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    ReviewType selectByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.review_type
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int updateByExampleSelective(@Param("row") ReviewType row, @Param("example") ReviewTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.review_type
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int updateByExample(@Param("row") ReviewType row, @Param("example") ReviewTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.review_type
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int updateByPrimaryKeySelective(ReviewType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.review_type
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int updateByPrimaryKey(ReviewType row);
}