package org.capten.live.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.capten.live.model.ReviewRecordComment;
import org.capten.live.model.ReviewRecordCommentExample;

public interface ReviewRecordCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.review_record_comment
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    long countByExample(ReviewRecordCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.review_record_comment
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int deleteByExample(ReviewRecordCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.review_record_comment
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int deleteByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.review_record_comment
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int insert(ReviewRecordComment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.review_record_comment
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int insertSelective(ReviewRecordComment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.review_record_comment
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    List<ReviewRecordComment> selectByExample(ReviewRecordCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.review_record_comment
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    ReviewRecordComment selectByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.review_record_comment
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int updateByExampleSelective(@Param("row") ReviewRecordComment row, @Param("example") ReviewRecordCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.review_record_comment
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int updateByExample(@Param("row") ReviewRecordComment row, @Param("example") ReviewRecordCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.review_record_comment
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int updateByPrimaryKeySelective(ReviewRecordComment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.review_record_comment
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int updateByPrimaryKey(ReviewRecordComment row);
}