package org.capten.live.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.capten.live.model.ReviewRecord;
import org.capten.live.model.ReviewRecordExample;

public interface ReviewRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.review_record
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    long countByExample(ReviewRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.review_record
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int deleteByExample(ReviewRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.review_record
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int deleteByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.review_record
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int insert(ReviewRecord row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.review_record
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int insertSelective(ReviewRecord row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.review_record
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    List<ReviewRecord> selectByExample(ReviewRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.review_record
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    ReviewRecord selectByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.review_record
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int updateByExampleSelective(@Param("row") ReviewRecord row, @Param("example") ReviewRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.review_record
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int updateByExample(@Param("row") ReviewRecord row, @Param("example") ReviewRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.review_record
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int updateByPrimaryKeySelective(ReviewRecord row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.review_record
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int updateByPrimaryKey(ReviewRecord row);
}