package org.capten.live.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.capten.live.model.RuntimeTaskTemplate;
import org.capten.live.model.RuntimeTaskTemplateExample;

public interface RuntimeTaskTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.runtime_task_template
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    long countByExample(RuntimeTaskTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.runtime_task_template
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int deleteByExample(RuntimeTaskTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.runtime_task_template
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int deleteByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.runtime_task_template
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int insert(RuntimeTaskTemplate row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.runtime_task_template
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int insertSelective(RuntimeTaskTemplate row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.runtime_task_template
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    List<RuntimeTaskTemplate> selectByExample(RuntimeTaskTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.runtime_task_template
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    RuntimeTaskTemplate selectByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.runtime_task_template
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int updateByExampleSelective(@Param("row") RuntimeTaskTemplate row, @Param("example") RuntimeTaskTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.runtime_task_template
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int updateByExample(@Param("row") RuntimeTaskTemplate row, @Param("example") RuntimeTaskTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.runtime_task_template
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int updateByPrimaryKeySelective(RuntimeTaskTemplate row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.runtime_task_template
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int updateByPrimaryKey(RuntimeTaskTemplate row);
}