package org.capten.live.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.capten.live.model.RuntimeTask;
import org.capten.live.model.RuntimeTaskExample;

public interface RuntimeTaskMapper extends BaseMapper<RuntimeTask> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.runtime_task
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    long countByExample(RuntimeTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.runtime_task
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int deleteByExample(RuntimeTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.runtime_task
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int deleteByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.runtime_task
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int insert(RuntimeTask row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.runtime_task
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    List<RuntimeTask> selectByExample(RuntimeTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.runtime_task
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    RuntimeTask selectByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.runtime_task
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int updateByExampleSelective(@Param("row") RuntimeTask row, @Param("example") RuntimeTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.runtime_task
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int updateByExample(@Param("row") RuntimeTask row, @Param("example") RuntimeTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.runtime_task
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int updateByPrimaryKey(RuntimeTask row);
}