package org.capten.live.mapper;

import java.util.List;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Param;
import org.capten.live.model.TasksIndex;
import org.capten.live.model.TasksIndexExample;

public interface TasksIndexMapper extends BaseMapper<TasksIndex> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tasks_index
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    long countByExample(TasksIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tasks_index
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int deleteByExample(TasksIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tasks_index
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tasks_index
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int insert(TasksIndex row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tasks_index
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int insertSelective(TasksIndex row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tasks_index
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    List<TasksIndex> selectByExample(TasksIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tasks_index
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    TasksIndex selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tasks_index
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int updateByExampleSelective(@Param("row") TasksIndex row, @Param("example") TasksIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tasks_index
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int updateByExample(@Param("row") TasksIndex row, @Param("example") TasksIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tasks_index
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int updateByPrimaryKeySelective(TasksIndex row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tasks_index
     *
     * @mbg.generated Wed Jan 22 22:27:35 CST 2025
     */
    int updateByPrimaryKey(TasksIndex row);
}