package org.capten.live.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.capten.live.model.Tasks;
import org.capten.live.model.TasksExample;

public interface TasksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tasks
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    long countByExample(TasksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tasks
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int deleteByExample(TasksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tasks
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int deleteByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tasks
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int insert(Tasks row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tasks
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int insertSelective(Tasks row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tasks
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    List<Tasks> selectByExample(TasksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tasks
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    Tasks selectByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tasks
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int updateByExampleSelective(@Param("row") Tasks row, @Param("example") TasksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tasks
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int updateByExample(@Param("row") Tasks row, @Param("example") TasksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tasks
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int updateByPrimaryKeySelective(Tasks row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tasks
     *
     * @mbg.generated Sun Jan 19 12:56:20 CST 2025
     */
    int updateByPrimaryKey(Tasks row);
}